apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: nextjs-sample-app
  app.kubernetes.io/instance: nextjs-sample-app-instance
  app.kubernetes.io/name: nextjs-sample-app
images:
- name: '*'
  newName: quay.io/jaspaul_khurana_ibm/nextjs-sample-app
  newTag: 1c9b50832a16431f1b6a122394da4dabc3c0a9ce
